version: "2.4"

services:
  php:
    build: ./docker/php8
    image: docker_ide_php
    cap_drop: [all]
    cap_add: [chown, setgid, setuid, kill]
    volumes:
      - ./:/var/www
    networks:
      - backend
    restart: unless-stopped
    stop_grace_period: 30s
    stop_signal: SIGQUIT
  nginx:
    image: nginx:stable-alpine
    cap_drop: [all]
    cap_add: [chown, setuid, setgid, dac_override, net_bind_service]
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    restart: unless-stopped
  code-server:
    build:
      context: ./docker/code-server
      args: [UID]
    cap_drop: [all]
    userns_mode: "host"
    volumes:
      - ./:/var/www
      - ./bin:/usr/local/sbin
      - ./docker/code-server/settings.json:/config/.local/share/code-server/User/settings.json
      - ./docker/code-server/tasks.json:/config/.local/share/code-server/User/tasks.json
      - ./docker/code-server/keybindings.json:/config/.local/share/code-server/User/keybindings.json
      - ./docker/code-server/launch.json:/var/www/.vscode/launch.json
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
