version: "2.1"

services:
  composer:
    image: docker_ide_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: composer-214.phar
    command: install --no-dev --no-cache --no-progress -o -a --ignore-platform-reqs
    volumes:
      - ./service/:/var/www
      - ./bin:/usr/local/sbin
  psalm:
    image: docker_ide_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: psalm-473.phar --no-cache
    volumes:
      - ./service/:/var/www
      - ./bin:/usr/local/sbin
  phpcsfixer:
    image: docker_ide_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: phpcsfixer-3000.phar fix --verbose --dry-run --diff --config phpcsfixer.conf
    volumes:
      - ./service/:/var/www
      - ./bin:/usr/local/sbin
  phpunit:
    image: docker_ide_php
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: phpunit-954.phar
    volumes:
      - ./service/:/var/www
      - ./bin:/usr/local/sbin
    networks:
      - backend
    links:
      - nginx
      - php

networks:
  backend:
    driver: bridge
